using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Handles enemy movement along the pathfinding route.
/// Controls enemy velocity, positioning, and animation following waypoints generated by the pathfinder.
/// </summary>
[RequireComponent(typeof(Enemy))]
public class EnemyMover : MonoBehaviour
{
    /// <summary>
    /// The movement speed of the enemy along the path (0-7 units per second).
    /// </summary>
    [SerializeField] [Range(0f, 7f)] private float speed = 0.7f;

    /// <summary>
    /// The current path the enemy is following, represented as a list of waypoint nodes.
    /// </summary>
    private List<Node> path = new List<Node>();

    /// <summary>
    /// Reference to the Enemy component for reward/penalty handling.
    /// </summary>
    private Enemy enemy;

    /// <summary>
    /// Reference to the GridManager for coordinate/position conversions.
    /// </summary>
    private GridManager gridManager;

    /// <summary>
    /// Reference to the Pathfinder for path calculations and recalculation requests.
    /// </summary>
    private Pathfinder pathfinder;

    /// <summary>
    /// Called when the enemy is enabled (spawned or reactivated).
    /// Resets position and recalculates the path.
    /// </summary>
    private void OnEnable()
    {
        ReturnToStart();
        RecalculatePath(true);
    }

    /// <summary>
    /// Initializes references to required components.
    /// Called before Start().
    /// </summary>
    private void Awake()
    {
        enemy = GetComponent<Enemy>();
        gridManager = FindFirstObjectByType<GridManager>();
        pathfinder = FindFirstObjectByType<Pathfinder>();
    }

    /// <summary>
    /// Recalculates the path from the enemy's current position or from the start.
    /// </summary>
    /// <param name="resetPath">If true, recalculates from the start coordinates. If false, from current position.</param>
    private void RecalculatePath(bool resetPath)
    {
        Vector2Int coordinates = new Vector2Int();
        if (resetPath)
        {
            coordinates = pathfinder.StartCoords;
        }
        else
        {
            coordinates = gridManager.GetCoordinatesFromPosition(transform.position);
        }

        StopAllCoroutines();
        path.Clear();
        path = pathfinder.GetNewPath(coordinates);
        StartCoroutine(FollowPath());
    }

    /// <summary>
    /// Resets the enemy to its starting position at the spawn point.
    /// </summary>
    private void ReturnToStart()
    {
        transform.position = gridManager.GetPositionFromCoordinates(pathfinder.StartCoords);
    }

    /// <summary>
    /// Coroutine that animates the enemy movement along the calculated path.
    /// Moves the enemy smoothly from waypoint to waypoint using Lerp interpolation.
    /// </summary>
    private IEnumerator FollowPath()
    {
        // Skip the first node (current position) and move to subsequent waypoints
        for (int i = 1; i < path.Count; i++)
        {
            Vector3 startPosition = transform.position;
            Vector3 endPosition = gridManager.GetPositionFromCoordinates(path[i].Coordinates);
            float travelPercent = 0f;
            
            // Orient enemy toward the next waypoint
            transform.LookAt(endPosition);

            // Smoothly interpolate from start to end position
            while (travelPercent < 1f)
            {
                travelPercent += Time.deltaTime * speed;
                transform.position = Vector3.Lerp(startPosition, endPosition, travelPercent);
                yield return new WaitForEndOfFrame();
            }
        }

        FinishPath();
    }

    /// <summary>
    /// Called when the enemy reaches the destination.
    /// Applies gold penalty and deactivates the enemy.
    /// </summary>
    private void FinishPath()
    {
        enemy.StealGold();
        gameObject.SetActive(false);
    }
}
